 language: python
    
 python: "3.6"
    
 git:
   depth: 1

  install:
    - pip install codecov

  script:
    - (run your unit tests with "coverage" to generate code coverage data)

  after_success:
    - codecov