 language: python
    
 python: "3.6"
    
 git:
   depth: 1

  install:
    - pip install codecov

  script:
    - coverage run fraction_test.py
    - python3 -m unittest discover -p "*_test.py"
    

  after_success:
    - codecov